// <auto-generated />
using System;
using HotelApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelApp.Data.Migrations
{
    [DbContext(typeof(HotelAppDbContext))]
    [Migration("20260101203445_AddBookingRoomRelationToStay")]
    partial class AddBookingRoomRelationToStay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HotelApp.Data.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Booking identifier");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("DateArrival")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateDeparture")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if booking is deleted");

                    b.Property<bool>("IsForAnotherPerson")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the booking is for another person");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Booking's manager");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Owner name of the booking");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasComment("Booking in the system");
                        });
                });

            modelBuilder.Entity("HotelApp.Data.Models.BookingRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("BookingRoom identifier");

                    b.Property<int>("AdultsCount")
                        .HasColumnType("int");

                    b.Property<int>("BabyCount")
                        .HasColumnType("int")
                        .HasComment("Baby age is between 0 and 3");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Booking identifier");

                    b.Property<int>("ChildCount")
                        .HasColumnType("int")
                        .HasComment("Child age is between 4 and 17");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if booking room is deleted");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Room identifier");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasComment("Status of the room reservation");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("StatusId");

                    b.HasIndex("BookingId", "RoomId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("BookingRooms", t =>
                        {
                            t.HasComment("Mapping table between Booking and Room");
                        });
                });

            modelBuilder.Entity("HotelApp.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Category identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Beds")
                        .HasColumnType("int")
                        .HasComment("Category beds count");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Category description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Category image URL");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if category is deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Category name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Category price");

                    b.HasKey("Id");

                    b.ToTable("Categories", t =>
                        {
                            t.HasComment("Category in the system");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beds = 2,
                            Description = "Modern and stylish design",
                            ImageUrl = "/images/upload/categories/7fb46e46-d4d6-41b8-8b54-9c81096462f1.jpg",
                            IsDeleted = false,
                            Name = "Double Room",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 2,
                            Beds = 3,
                            Description = "Convenience for all the family",
                            ImageUrl = "/images/upload/categories/3ce40dc4-f2a7-4cf1-97e6-3d9e68f892fe.jpg",
                            IsDeleted = false,
                            Name = "Family Room",
                            Price = 500.00m
                        },
                        new
                        {
                            Id = 3,
                            Beds = 4,
                            Description = "Modern design, comfort and convenience",
                            ImageUrl = "/images/upload/categories/b77081e5-111e-4220-a122-597e46708efd.jpg",
                            IsDeleted = false,
                            Name = "Apartment",
                            Price = 1000.00m
                        },
                        new
                        {
                            Id = 4,
                            Beds = 2,
                            Description = "Luxury, elegance and comfort",
                            ImageUrl = "/images/upload/categories/e3d7e66a-aebd-45d7-9ad4-04f65c2704f6.jpg",
                            IsDeleted = false,
                            Name = "Double Room L",
                            Price = 400.00m
                        },
                        new
                        {
                            Id = 5,
                            Beds = 4,
                            Description = "Luxury, elegance and comfort",
                            ImageUrl = "/images/upload/categories/44e74722-5f1d-4736-bf28-bc7d914a9192.jpg",
                            IsDeleted = false,
                            Name = "Apartment L",
                            Price = 1500.00m
                        },
                        new
                        {
                            Id = 6,
                            Beds = 4,
                            Description = "Super luxury, elegance and comfort",
                            ImageUrl = "/images/upload/categories/7aa43c19-831a-4890-bd6e-dded11e88d3f.jpg",
                            IsDeleted = false,
                            Name = "Apartment Super L",
                            Price = 2000.00m
                        });
                });

            modelBuilder.Entity("HotelApp.Data.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Manager identifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Manager's user entity");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Managers", t =>
                        {
                            t.HasComment("Manager in the system");
                        });
                });

            modelBuilder.Entity("HotelApp.Data.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if payment is deleted");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentUserFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentUserPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HotelApp.Data.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Payment identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if payment method is deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Payment name");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods", t =>
                        {
                            t.HasComment("Payment method in the system");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Bank Transfer"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Cashe"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Debit Card/ Credit Card"
                        });
                });

            modelBuilder.Entity("HotelApp.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Room identifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if room is deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("Room name(number)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Rooms", t =>
                        {
                            t.HasComment("Room in the system");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae50a5ab-9642-466f-b528-3cc61071bb4c"),
                            CategoryId = 1,
                            IsDeleted = false,
                            Name = "201"
                        },
                        new
                        {
                            Id = new Guid("777634e2-3bb6-4748-8e91-7a10b70c78ac"),
                            CategoryId = 1,
                            IsDeleted = false,
                            Name = "202"
                        },
                        new
                        {
                            Id = new Guid("68fb84b9-ef2a-402f-b4fc-595006f5c275"),
                            CategoryId = 1,
                            IsDeleted = false,
                            Name = "203"
                        },
                        new
                        {
                            Id = new Guid("c1bd2a4a-6f9b-4daf-a0bb-4f7cdccf6101"),
                            CategoryId = 2,
                            IsDeleted = false,
                            Name = "301"
                        },
                        new
                        {
                            Id = new Guid("bfb7b7af-d533-4b7e-a7a9-69d27e0e5d47"),
                            CategoryId = 2,
                            IsDeleted = false,
                            Name = "302"
                        },
                        new
                        {
                            Id = new Guid("ee45d08c-f4d7-4b87-9ceb-6157c703a7dc"),
                            CategoryId = 2,
                            IsDeleted = false,
                            Name = "303"
                        },
                        new
                        {
                            Id = new Guid("f1e8ce5d-8c16-4bf6-9ff6-70db57fcd118"),
                            CategoryId = 3,
                            IsDeleted = false,
                            Name = "401"
                        },
                        new
                        {
                            Id = new Guid("40c553a9-f28f-4d17-bd83-92fd2c63ff91"),
                            CategoryId = 3,
                            IsDeleted = false,
                            Name = "402"
                        },
                        new
                        {
                            Id = new Guid("fbb4b2e4-7319-45a7-ac07-fe7e7345d5cb"),
                            CategoryId = 3,
                            IsDeleted = false,
                            Name = "403"
                        },
                        new
                        {
                            Id = new Guid("c6d17679-1de6-4cbb-b625-408b7bff3dc4"),
                            CategoryId = 4,
                            IsDeleted = false,
                            Name = "501"
                        },
                        new
                        {
                            Id = new Guid("7f48c43a-8c88-486b-a59e-0e89bd4453ec"),
                            CategoryId = 4,
                            IsDeleted = false,
                            Name = "502"
                        },
                        new
                        {
                            Id = new Guid("e76e6f0c-e838-4f47-b836-882b7ccc6983"),
                            CategoryId = 4,
                            IsDeleted = false,
                            Name = "503"
                        },
                        new
                        {
                            Id = new Guid("a93c5830-33fb-4d67-b8d8-468ed20c5efd"),
                            CategoryId = 5,
                            IsDeleted = false,
                            Name = "601"
                        },
                        new
                        {
                            Id = new Guid("8ffd66e2-7938-4e62-a246-f63cd583f2de"),
                            CategoryId = 5,
                            IsDeleted = false,
                            Name = "602"
                        },
                        new
                        {
                            Id = new Guid("d5f93a83-98f4-46a9-85da-ff2f3282e6f5"),
                            CategoryId = 5,
                            IsDeleted = false,
                            Name = "603"
                        },
                        new
                        {
                            Id = new Guid("41c54c25-a26f-41e2-95a0-e58210f8506e"),
                            CategoryId = 6,
                            IsDeleted = false,
                            Name = "701"
                        },
                        new
                        {
                            Id = new Guid("22b64510-5d86-41e4-869e-04e7a76374dc"),
                            CategoryId = 6,
                            IsDeleted = false,
                            Name = "702"
                        },
                        new
                        {
                            Id = new Guid("a4a36a83-1f95-47f7-a1c6-91c116b033ef"),
                            CategoryId = 6,
                            IsDeleted = false,
                            Name = "703"
                        });
                });

            modelBuilder.Entity("HotelApp.Data.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Status identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if status is deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Status name");

                    b.HasKey("Id");

                    b.ToTable("Statuses", t =>
                        {
                            t.HasComment("Booking status in the system");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Awaiting Payment"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "For Implementation"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Done"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Done - Early Check Out"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Done - No Guests"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Done - Partial Attendance"
                        });
                });

            modelBuilder.Entity("HotelApp.Data.Models.Stay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CheckoutOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if stay is deleted");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("BookingRoomId");

                    b.HasIndex("GuestId");

                    b.ToTable("Stays");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HotelApp.Data.Models.Booking", b =>
                {
                    b.HasOne("HotelApp.Data.Models.Manager", "Manager")
                        .WithMany("ManagedBookings")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HotelApp.Data.Models.Status", "Status")
                        .WithMany("Bookings")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelApp.Data.Models.ApplicationUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelApp.Data.Models.BookingRoom", b =>
                {
                    b.HasOne("HotelApp.Data.Models.Booking", "Booking")
                        .WithMany("BookingRooms")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelApp.Data.Models.Room", "Room")
                        .WithMany("BookingRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelApp.Data.Models.Status", "Status")
                        .WithMany("BookingRooms")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Room");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Manager", b =>
                {
                    b.HasOne("HotelApp.Data.Models.ApplicationUser", "User")
                        .WithOne("Manager")
                        .HasForeignKey("HotelApp.Data.Models.Manager", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Payment", b =>
                {
                    b.HasOne("HotelApp.Data.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelApp.Data.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Room", b =>
                {
                    b.HasOne("HotelApp.Data.Models.Category", "Category")
                        .WithMany("Rooms")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Stay", b =>
                {
                    b.HasOne("HotelApp.Data.Models.Booking", "Booking")
                        .WithMany("Stays")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelApp.Data.Models.BookingRoom", "BookingRoom")
                        .WithMany("Stays")
                        .HasForeignKey("BookingRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelApp.Data.Models.Guest", "Guest")
                        .WithMany("Stays")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("BookingRoom");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HotelApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HotelApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HotelApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelApp.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Booking", b =>
                {
                    b.Navigation("BookingRooms");

                    b.Navigation("Payments");

                    b.Navigation("Stays");
                });

            modelBuilder.Entity("HotelApp.Data.Models.BookingRoom", b =>
                {
                    b.Navigation("Stays");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Category", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Guest", b =>
                {
                    b.Navigation("Stays");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Manager", b =>
                {
                    b.Navigation("ManagedBookings");
                });

            modelBuilder.Entity("HotelApp.Data.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Room", b =>
                {
                    b.Navigation("BookingRooms");
                });

            modelBuilder.Entity("HotelApp.Data.Models.Status", b =>
                {
                    b.Navigation("BookingRooms");

                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
